### ISSUE TITLE
add backward compatibility for layers_to_use

### ISSUE THREAD

**Issue by tomasohara** [machamp-nlp/machamp#18]
Hi, it would be good if backward compatibility were added for the new dataset parameter layers_to_use. This way, the dataset configurations can be shared across Machamp versions.

This can be done as follows:

```
$ git diff machamp/models/tag_decoder.py | cat
diff --git a/machamp/models/tag_decoder.py b/machamp/models/tag_decoder.py
index c334806..20d656d 100644
--- a/machamp/models/tag_decoder.py
+++ b/machamp/models/tag_decoder.py
@@ -51,7 +51,9 @@ class MachampTagger(Model):
         dataset_embeds_dim: int = 0,
         **kwargs,
     ) -> None:
-        super().__init__(vocab, **kwargs)
+        kwargs_allen = kwargs.copy()
+        del kwargs_allen["layers_to_use"]
+        super().__init__(vocab, **kwargs_allen)
 
         self.task = task
         self.vocab = vocab
```

Note that this is an expedient until Machamp stabilizes (e.g., to facilitate comparisons). In addition, it would seem better if the layers_to_use were put in a separate parameters file (e.g., to allow for larger models).

**Comment by robvanderg** [comment]
Hi, thanks for the suggestion and the fix. I am not in favor of this fix; because if it set to true, it gives the false impression that layer attention is used. It might be preferrable to give a warning (and/or exit) instead. What do you think about that solution?

**Comment by tomasohara** [comment]
As this is only meant as an expedient, having it conditioned upon an environment variable might be an alternative:

```
+        if ("IGNORE_LAYERS" in os.environ) and ("layers_to_use" in kwargs):
+            kwargs = kwargs.copy()
+            del kwargs["layers_to_use"]
         super().__init__(vocab, **kwargs)
```

In retrospect, I can patch this in a local version: the old allennlp-based branch probably won't change much.
