### ISSUE TITLE
Mismatch between f1 numbers and total number of lines

### ISSUE THREAD

**Issue by kategerasimenko** [machamp-nlp/machamp#20]
In [this function](https://github.com/machamp-nlp/machamp/blob/master/machamp/metrics/f1.py#L62), if I calculate `sum(self.tps) + sum(self.fps)` (or `sum(self.tps) + sum(self.fns)`, it's the same), I should get the total number of lines in the dataset but the numbers are different (either smaller or bigger). Moreover, this number changes every evaluation. Is there a bug somewhere or there's a flaw in my logic?

**Comment by robvanderg** [comment]
Thanks for reporting the issue, I expect to have time to look into this next week

**Comment by robvanderg** [comment]
I do not think they should equal the total lines in the dataset, because the true negatives are not taken into account. Did you cross-check the results with post-evaluating with sklearn after training? I tested this for the macro-f1, and it matched exactly.

**Comment by kategerasimenko** [comment]
What I mean is that `sum(self.tps) + sum(self.fps)` sum up to the total number of predictions of the model, and for classification, the model predicts something for every dataset item. Also what I noticed recently - this mismatch appears only in multitask setup, i.e. if I train the model on one dataset only, the score during training is the same as my external evaluation. I haven't checked the sum itself though.

**Comment by robvanderg** [comment]
Did you give your tasks the same name (note: https://github.com/machamp-nlp/machamp#training-on-multiple-datasets)? could you share your dataset configuration?

**Comment by kategerasimenko** [comment]
All my tasks differ (one task per dataset, one dataset per task). I can prepare some opensource data and configs for this and also adjacent issue next week.

**Comment by kategerasimenko** [comment]
Hello! Sorry for the delayed reply, here's the [colab notebook](https://colab.research.google.com/drive/1CQz2fjbInhSQjEYeRa5YB8htfbu80sJx?usp=sharing) with both issues. 

For this issue, I inserted a print of `sum(self.tps) + sum(self.fps)` in `f1.py`. The mismatch in number of examples (both train and dev) can be seen in the logs at every epoch.

**Comment by robvanderg** [comment]
Thanks for the notebook!, I have found the issue and resolved it

**Comment by robvanderg** [comment]
Thanks for the notebook; there was indeed an error, introduced on march 7th. It ran the evaluation too many times.
