### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/proc/27411/status'

### ISSUE THREAD

**Issue by veraDanilova** [machamp-nlp/machamp#22]
Hello! I get this error when running machamp from pycharm on mac os ventura 13.1 (in callback.py after sucessful evaluation on dev in the 1st epoch). 
I've read that on mac there is no proc/pid/status and I cannot find info on how to access the process data (the correct path on mac). Please, help me to fix this issue.

**Comment by robvanderg** [comment]
Hi Vera, 

Thanks for your issue, it seems like I made some assumptions on how to get the RAM that do not hold for mac os. I have now build in a check, and it shouldnt crash anymore. However, it will not report RAM usage in your case (as I am unsure how to easily obtain it.).

If you pull, it should work.

Best, 
Rob

**Comment by veraDanilova** [comment]
It works, thank you.
