### ISSUE TITLE
zero LAS in .out.eval and logs

### ISSUE THREAD

**Issue by veraDanilova** [machamp-nlp/machamp#23]
Hello! During training the output curves were ok, but LAS were 0.0. The scores for other metrics were ok. In the resulting .out.eval files LAS were also zero. Found that LAS is not calculated, because `gold_head_indices` are empty in `dependency_decoder.py.`  An empty dict is passed instead of `golds` to the forward function called from `get_output_labels` in machamp.py. When I substitute it with `golds` the scores are calculated.
Now I have this and it works (correctly?):
`_, mlm_out_token, mlm_out_sent, mlm_out_tok, mlm_preds, _ = self.forward(input_token_ids, golds, seg_ids,
                                                                                 eval_mask, offsets,
                                                                                 subword_mask, True)`

**Comment by robvanderg** [comment]
Thanks for the issue! I havent ran into this behaviour myself. Did you replace this line?:
https://github.com/machamp-nlp/machamp/blob/master/machamp/model/machamp.py#L345

**Comment by veraDanilova** [comment]
Yes, this one.

**Comment by robvanderg** [comment]
I am on holiday currently, will update it next week. Thanks again for the notification
