### ISSUE TITLE
Do tokenizers have to be slow?

### ISSUE THREAD

**Issue by LoicGrobol** [machamp-nlp/machamp#35]
[Currently](https://github.com/machamp-nlp/machamp/blob/29865e8778b1236f2a624ce6edacdd503ea7a9ae/machamp/data/machamp_dataset_collection.py#L62) tokenizers are forcibly loaded as slow, but it's not always possible: for instance tokenizers saved from `RobertaTokenizerFast` don't provide a slow version ([since](https://github.com/huggingface/transformers/issues/21289) that would require to generate a `sentencepiece` model from the `tokenizers` one, something that's currently not supported). As a result, trying to use one of the models (e.g. [`lgrobol/xlm-r+CreoleEval_all`](http://huggingface.co/lgrobol/xlm-r+CreoleEval_all) currently fails.

As a temporary fix I have tried to remove `use_fast=False` from the dataset collection code ans everything seems to work fine. Am I missing something? Is there still a reason for forcing the use of a slow tokenizer or can this be removed?

**Comment by robvanderg** [comment]
Hmm, I'd rather have a check in place and use the slow one when it is available. I tried to tokenize the whole UD with mBERT fast and slow a couple years back, and the fast one led to many more character differences. One of the strangest example being:

>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')
>>> tokenizer.decode(tokenizer.encode("do not"))
"[CLS] don't [SEP]"

**Comment by robvanderg** [comment]
Ok, I surrounded it in a try-except block for now, seems like a robust solution

**Comment by LoicGrobol** [comment]
Wow, this is so bizarre, I had no idea. Anyway, thank you for the quick fix!
